# Generated by Django 5.2 on 2025-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.RemoveField(
            model_name="addressobject",
            name="parent_item_1",
        ),
        migrations.RemoveField(
            model_name="addressobject",
            name="parent_item_2",
        ),
        migrations.RemoveField(
            model_name="addressobject",
            name="parent_item_3",
        ),
        migrations.RemoveField(
            model_name="addressobject",
            name="parent_item_4",
        ),
        migrations.AlterField(
            model_name="addressobject",
            name="hierarchy",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Select object's hierarchy in address",
                max_digits=2,
                verbose_name="object hierarchy",
            ),
        ),
    ]
