# Generated by Django 5.2 on 2025-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_delete_address_remove_addressobject_parent_item_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialword",
            name="popularity",
            field=models.PositiveIntegerField(
                default=0, help_text="Fills in automatically", verbose_name="province popularity"
            ),
        ),
    ]
